global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  # 1. Scrape Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      # Prometheus runs natively on 9090 inside its container
      - targets: ['localhost:9090'] 

  # 2. Scrape your FastAPI Backend
  - job_name: 'cs3-backend'
    scrape_interval: 5s
    static_configs:
      # Point this to your server and backend port
      - targets: ['paffenroth-23.dyn.wpi.edu:22092']